$axure.loadCurrentPage({
  "url":"客服聊天—普通客户.html",
  "generationDate":new Date(1418371264301.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dba2b6ccc16e4ae084eecfffaad0b3a0",
    "type":"Axure:Page",
    "name":"客服聊天—普通客户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2c6f2b68a63847558946ed393f6863a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":-10,
              "y":45},
            "size":{
              "width":1140,
              "height":760},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"609031f104494d60bd44526a5bbed147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":-10,
                  "y":45},
                "size":{
                  "width":1140,
                  "height":760},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u0.png"}},
{
          "id":"bebd34e4ab484496af482f219f7bc58d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":184,
              "y":70},
            "size":{
              "width":578,
              "height":710},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7564a70004f3428a96896f7ca96a1bab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":184,
                  "y":70},
                "size":{
                  "width":578,
                  "height":710},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u2.png"}},
{
          "id":"ab92b06de9e54a1594290ef1a01f8ef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":14,
              "y":70},
            "size":{
              "width":160,
              "height":710},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb6ec0a0ae33467ba3575fe43e8b5000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":70},
                "size":{
                  "width":160,
                  "height":710},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u6.png"}},
{
          "id":"51e6fccb8ee841e4a4a158846ca8a356",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":14,
              "y":132},
            "size":{
              "width":160,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eedc5b9bf360448989d06852c229b534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":14,
                  "y":132},
                "size":{
                  "width":160,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u8.png"}},
{
          "id":"378d4ce2cc884948a0e41a47e81e8938",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":14,
              "y":174},
            "size":{
              "width":160,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd1c507928864fc1b6d5b88290b0ce1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":14,
                  "y":174},
                "size":{
                  "width":160,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u8.png"}},
{
          "id":"fd77e13127f048d88c26153028230a4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":14,
              "y":174},
            "size":{
              "width":160,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e00c948942174b6481658281ed587f1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":14,
                  "y":174},
                "size":{
                  "width":160,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u12.png"}},
{
          "id":"8acc7582526f4cf6838881102ee8eb88",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":14,
              "y":258},
            "size":{
              "width":160,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"098310d017bf4447adbfc72d09854b1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":14,
                  "y":258},
                "size":{
                  "width":160,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u8.png"}},
{
          "id":"5e5ab54374184b6eaa82afae2dda1bb6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":14,
              "y":300},
            "size":{
              "width":160,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4317708823114995886786887998c9cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":14,
                  "y":300},
                "size":{
                  "width":160,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u8.png"}},
{
          "id":"0032658b888c4d7c8a7f239fe9c9e840",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":14,
              "y":342},
            "size":{
              "width":160,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa62478ea2a64959b1cde034298a3e47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":14,
                  "y":342},
                "size":{
                  "width":160,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u8.png"}},
{
          "id":"75dddd310d7b49d198bb9639760593b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":14,
              "y":384},
            "size":{
              "width":160,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e45d75d85c243a495602c851eda003e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":14,
                  "y":384},
                "size":{
                  "width":160,
                  "height":42},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u8.png"}},
{
          "id":"ebba288138164241a7dbb5797d753974",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":127},
            "size":{
              "width":158,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u24_line.png"}},
{
          "id":"6665915837584acc81443c5ac6f11894",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B6B6B},
            "location":{
              "x":138,
              "y":272},
            "size":{
              "width":16,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb8c393f809149aa87b7cc0353bfe2ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B},
                "location":{
                  "x":138,
                  "y":272},
                "size":{
                  "width":16,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u33.png"}},
{
          "id":"42e3cd6cdaae4418868049caa433f8e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B6B6B},
            "location":{
              "x":138,
              "y":314},
            "size":{
              "width":16,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ace46d7e502746f38b96538d512ed5b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B},
                "location":{
                  "x":138,
                  "y":314},
                "size":{
                  "width":16,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u33.png"}},
{
          "id":"80d98a8d8a7944b980c5a3a33c0d08c6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":184,
              "y":620},
            "size":{
              "width":578,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u49_line.png"}},
{
          "id":"f3f9bf2e03c74ae385fb3ddf544d3aa6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":258,
              "y":92},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8445c63071424e749d6aff5d2f443876",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":258,
                  "y":92},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ea69634a8ef4ed1a215d5115c598e80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":204,
              "y":641},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d517e4a2a354864ba0ad32b482165cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":641},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2efbdec5e3f14dada532cec019dc73b1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":127},
            "size":{
              "width":576,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u62_line.png"}},
{
          "id":"09244078185f42cba457048e39363ec0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":755,
              "y":133},
            "size":{
              "width":6,
              "height":410},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d391f881c32740d0b59c95b5118b863b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":755,
                  "y":133},
                "size":{
                  "width":6,
                  "height":410},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u67.png"}},
{
          "id":"41139b3b11c84b109b5ca4b4079035c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF6B6B6B},
            "location":{
              "x":138,
              "y":229},
            "size":{
              "width":16,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c72eede64a4f48008a74e4c70d8c72f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B},
                "location":{
                  "x":138,
                  "y":229},
                "size":{
                  "width":16,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u33.png"}},
{
          "id":"2fa0742f3c1e42fa8c1b118876560f00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":204,
              "y":82},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e78827c7ed34725b579398974d5e2be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":204,
                  "y":82},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u79.png"}},
{
          "id":"e2980584508645288f286f02eb630389",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":665,
              "y":88},
            "size":{
              "width":76,
              "height":25},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"444782e816634562b39346372fbe9be3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":665,
                  "y":88},
                "size":{
                  "width":76,
                  "height":25},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 客服聊天_转接popup in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"客服聊天_转接popup.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/客服聊天/u93.png"}},
{
          "id":"6ca1f4e8eafe457dbba374c3ba02a0e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":61,
              "y":144},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9f2d10dcfb244e796bdfa465a2cedb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":144},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"773d07981eb84905bdf8402b3709055e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":61,
              "y":270},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8863002775c341019bb8980c639db999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":270},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3046b44e6d454374a76bfdde5cc8f92f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":61,
              "y":186},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fbb644d67ef44e3a6a1e4b3914e6a99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":186},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9f2932248b646cfa61c398ba63cc1e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":61,
              "y":229},
            "size":{
              "width":38,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e75b6bf645f843a68426dc55c2390319",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":229},
                "size":{
                  "width":38,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af11b472a79d4e3b8b9939fedd1767c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":61,
              "y":312},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"365f9b44b0f34dd383a7e29412a30dd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":312},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3367eaafee59456db7f51b9ee2ad2c49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":61,
              "y":354},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fec887d2f2e948e09f00137ab8b6202d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":354},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad8acf4c0ec44cc8879324c8d920c564",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":61,
              "y":397},
            "size":{
              "width":29,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd3e6fdb76184181b6f3b4c8e2122109",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":397},
                "size":{
                  "width":29,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1ecd6ed518843febc9290398e5bbb61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":34,
              "y":143},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39dcc50dcab64479979e89ad2539041a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":34,
                  "y":143},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u101.png"}},
{
          "id":"41c4291aa9aa4eb7aeb3bffb805ceacd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":34,
              "y":186},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b1f26e8580443aaa4e1d65d165cec7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":34,
                  "y":186},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u101.png"}},
{
          "id":"b4a6fa044d494d40897b1d88ba9f5ea3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":34,
              "y":227},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3887003dbc02470ca738b9fc4855933f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":34,
                  "y":227},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u101.png"}},
{
          "id":"30cf6c1c6cf243f989f891b82e15dae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":34,
              "y":269},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dad18ccb7044358baf90ac278653aa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":34,
                  "y":269},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u101.png"}},
{
          "id":"0ad177ba3f2f44ce944740e69d2463fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":34,
              "y":311},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9eab07c7e694be7ac0a114d6a348ecd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":34,
                  "y":311},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u101.png"}},
{
          "id":"e41ba5166f7641239a6bc19503c5afbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":34,
              "y":354},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e93467f6f31e4957a5835569d0bdfd1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":34,
                  "y":354},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u101.png"}},
{
          "id":"7eec22ec501140f09b6c7242eb27142f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":34,
              "y":396},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e828bad83be48fe9e2406c7aa2153b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":34,
                  "y":396},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u101.png"}},
{
          "id":"ccad348ec7964908bad29f5a41a2fa8a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6a5acbfcf24142c6b12dd54905974233"},
{
          "id":"82d0db73e4ab468d9d4d42273fe4c786",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFC9C9C9},
            "location":{
              "x":300,
              "y":95},
            "size":{
              "width":190,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1377580c4964b178578c5c61cf757b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9},
                "location":{
                  "x":300,
                  "y":95},
                "size":{
                  "width":190,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u4.png"}},
{
          "id":"181a51c6852d4345b2af012dbe4f3ef5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":34,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c191a1e114947bd8dfc167ca6f1daff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":34,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3940464547ff4bcfa5bfa88d6e21d4ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":317,
              "y":94},
            "size":{
              "width":163,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e46b61a7684a40518fc1f4305dfe730a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":317,
                  "y":94},
                "size":{
                  "width":163,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84f60f2b764a4a26b6938dfd6cb94bf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":542,
              "y":194},
            "size":{
              "width":145,
              "height":37},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42cd09d72dec4163ab779f23c9a9d7cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":542,
                  "y":194},
                "size":{
                  "width":145,
                  "height":37},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u56.png"}},
{
          "id":"de60f6d0c9db4320883a2d7282248856",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":706,
              "y":193},
            "size":{
              "width":36,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5c2bd71f72345fdb5061f6d62f91264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":706,
                  "y":193},
                "size":{
                  "width":36,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u164.png"}},
{
          "id":"32e3fe3e820f4386b64eee0fa929c316",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":667,
              "y":194},
            "size":{
              "width":29,
              "height":13},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e42e66a7a5c43ed9d306c0e1606a97d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":667,
                  "y":194},
                "size":{
                  "width":29,
                  "height":13},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u170.png"}},
{
          "id":"94d91d85e9f54404a52fd8a38ec9cf28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":667,
              "y":195},
            "size":{
              "width":19,
              "height":12},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c868d7af5104c1fad79a8fa2965927d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":667,
                  "y":195},
                "size":{
                  "width":19,
                  "height":12},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u172.png"}},
{
          "id":"437e1a5fb53a4f45934d828865a0fcdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"11px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":393,
              "y":160},
            "size":{
              "width":181,
              "height":14},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3316172fd1e74cce84c13b93c812543a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"11px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":393,
                  "y":160},
                "size":{
                  "width":181,
                  "height":14},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9d5de06c1714faf89b59fab251a5357",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":163},
            "size":{
              "width":86,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u83_line.png"}},
{
          "id":"ebbafca1f32e444faafebbffa9ff8d6f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":566,
              "y":163},
            "size":{
              "width":86,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u83_line.png"}},
{
          "id":"2e961e49df2a43eeb3bad0bf9c4985ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":774,
              "y":70},
            "size":{
              "width":333,
              "height":710},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eea246128384f2d96c7b4774be54a78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":774,
                  "y":70},
                "size":{
                  "width":333,
                  "height":710},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天_知识库/u20.png"}},
{
          "id":"eb69c3fb500e4fc694da9f37049fde95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":793,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51b25f852bf04e00a539ca788514eaee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":793,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb5971349ef844abaac52f3d908fc82b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":127},
            "size":{
              "width":332,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u69_line.png"}},
{
          "id":"0b42320f900343ae948b5d2a7e986567",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF7D7D86},
            "location":{
              "x":793,
              "y":130},
            "size":{
              "width":64,
              "height":2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dfedf5c7c1b41c7a7649cbe4f8417f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7D7D86},
                "location":{
                  "x":793,
                  "y":130},
                "size":{
                  "width":64,
                  "height":2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u89.png"}},
{
          "id":"147672b948ef4835aa46dd8585e29c6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":869,
              "y":92},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18308ae527504649b82707dd14c27a01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":869,
                  "y":92},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 客服聊天_知识库 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"客服聊天_知识库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3af8d9eef635442eb0a292636a2b5d9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":894,
              "y":347},
            "size":{
              "width":92,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"073f324d68904061812580ead14a82b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":894,
                  "y":347},
                "size":{
                  "width":92,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc83912eb95d4535b4bb8de7fc2d0e0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":666,
              "y":732},
            "size":{
              "width":76,
              "height":25},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67fc779c61af4b0cb419f2057447b53c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":666,
                  "y":732},
                "size":{
                  "width":76,
                  "height":25},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u93.png"}},
{
          "id":"da3f158af2c94616bc3f4078a4c8cf69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":576,
              "y":732},
            "size":{
              "width":76,
              "height":25},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5869b078bbcb4e66818152fdd8423b3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":576,
                  "y":732},
                "size":{
                  "width":76,
                  "height":25},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u97.png"}}]}},
  "masters":{
    "6a5acbfcf24142c6b12dd54905974233":{
      "packageId":"6a5acbfcf24142c6b12dd54905974233",
      "type":"Axure:Master",
      "name":"Title_客服聊天（客服管理员）有消息",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"cf36703323f84d5da0ce305eb182243e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":410,
                "y":26},
              "size":{
                "width":12,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92f36235e937429f927d3bc44ef581ce",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":410,
                    "y":26},
                  "size":{
                    "width":12,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u126.png"}},
{
            "id":"e8721cdf67cb4fb1893fb7ecd42e1508",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":260,
                "y":17},
              "size":{
                "width":120,
                "height":24},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5593caf6b6b942d5a16e962a1ff9225f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":260,
                    "y":17},
                  "size":{
                    "width":120,
                    "height":24},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1e13684f9cde432b9af9ff2a2cbb951e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFF363636},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":890,
                "height":45},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF1B1B1B}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"074ed56cac3f4bd3a1db4cd2db90be85",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF363636},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":890,
                    "height":45},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF1B1B1B}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u130.png"}},
{
            "id":"ee7b1c95956747db81d43c22427a046d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF363636},
              "size":{
                "width":240,
                "height":45},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF1B1B1B}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c5567bf4d2894ac8bac3e7e3e270f43a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF363636},
                  "size":{
                    "width":240,
                    "height":45},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF1B1B1B}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u132.png"}},
{
            "id":"957b9c5f50644e83bd97d36c40341a9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":951,
                "y":14},
              "size":{
                "width":52,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b92c3b0bdb81435b855b410bc712bcb3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":951,
                    "y":14},
                  "size":{
                    "width":52,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 客服聊天_编辑admin in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"客服聊天_编辑admin.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f68dea9c69bd450ab354f08dc9755c6e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":917,
                "y":11.5},
              "size":{
                "width":22,
                "height":22},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fd6f29cac81424d821b64d82b778a9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":917,
                    "y":11.5},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u136.png"}},
{
            "id":"f7a0ac41e312402b9055d9b720c63f14",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":921,
                "y":15.5},
              "size":{
                "width":15,
                "height":15},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45a480de6a584173a81c25899a5ec914",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":921,
                    "y":15.5},
                  "size":{
                    "width":15,
                    "height":15},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u138.png"}},
{
            "id":"fa6acc37cd7c4e1bb7684fcfd584b746",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":807,
                "y":14},
              "size":{
                "width":83,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d802ab836a0e4cfe9f2ca5738e0c6b96",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":807,
                    "y":14},
                  "size":{
                    "width":83,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 客服聊天—消息 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"客服聊天—消息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7d8f1f8447844dc0883e7817fa70ed53",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFFB00000},
              "location":{
                "x":829,
                "y":8},
              "size":{
                "width":14,
                "height":14},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b69c5652827943c6a9650955bda3dc52",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFB00000},
                  "location":{
                    "x":829,
                    "y":8},
                  "size":{
                    "width":14,
                    "height":14},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u142.png"}},
{
            "id":"ef3af0ed24b8426fb01a6e4018215ff5",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":833,
                "y":8},
              "size":{
                "width":8,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2092eb4d66124ed48789ad98e6c8129a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":833,
                    "y":8},
                  "size":{
                    "width":8,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "2c6f2b68a63847558946ed393f6863a4":{
      "scriptId":"u0"},
    "609031f104494d60bd44526a5bbed147":{
      "scriptId":"u1"},
    "bebd34e4ab484496af482f219f7bc58d":{
      "scriptId":"u2"},
    "7564a70004f3428a96896f7ca96a1bab":{
      "scriptId":"u3"},
    "ab92b06de9e54a1594290ef1a01f8ef4":{
      "scriptId":"u4"},
    "eb6ec0a0ae33467ba3575fe43e8b5000":{
      "scriptId":"u5"},
    "51e6fccb8ee841e4a4a158846ca8a356":{
      "scriptId":"u6"},
    "eedc5b9bf360448989d06852c229b534":{
      "scriptId":"u7"},
    "378d4ce2cc884948a0e41a47e81e8938":{
      "scriptId":"u8"},
    "dd1c507928864fc1b6d5b88290b0ce1d":{
      "scriptId":"u9"},
    "fd77e13127f048d88c26153028230a4e":{
      "scriptId":"u10"},
    "e00c948942174b6481658281ed587f1a":{
      "scriptId":"u11"},
    "8acc7582526f4cf6838881102ee8eb88":{
      "scriptId":"u12"},
    "098310d017bf4447adbfc72d09854b1b":{
      "scriptId":"u13"},
    "5e5ab54374184b6eaa82afae2dda1bb6":{
      "scriptId":"u14"},
    "4317708823114995886786887998c9cc":{
      "scriptId":"u15"},
    "0032658b888c4d7c8a7f239fe9c9e840":{
      "scriptId":"u16"},
    "fa62478ea2a64959b1cde034298a3e47":{
      "scriptId":"u17"},
    "75dddd310d7b49d198bb9639760593b0":{
      "scriptId":"u18"},
    "1e45d75d85c243a495602c851eda003e":{
      "scriptId":"u19"},
    "ebba288138164241a7dbb5797d753974":{
      "scriptId":"u20"},
    "6665915837584acc81443c5ac6f11894":{
      "scriptId":"u21"},
    "cb8c393f809149aa87b7cc0353bfe2ab":{
      "scriptId":"u22"},
    "42e3cd6cdaae4418868049caa433f8e5":{
      "scriptId":"u23"},
    "ace46d7e502746f38b96538d512ed5b4":{
      "scriptId":"u24"},
    "80d98a8d8a7944b980c5a3a33c0d08c6":{
      "scriptId":"u25"},
    "f3f9bf2e03c74ae385fb3ddf544d3aa6":{
      "scriptId":"u26"},
    "8445c63071424e749d6aff5d2f443876":{
      "scriptId":"u27"},
    "7ea69634a8ef4ed1a215d5115c598e80":{
      "scriptId":"u28"},
    "5d517e4a2a354864ba0ad32b482165cb":{
      "scriptId":"u29"},
    "2efbdec5e3f14dada532cec019dc73b1":{
      "scriptId":"u30"},
    "09244078185f42cba457048e39363ec0":{
      "scriptId":"u31"},
    "d391f881c32740d0b59c95b5118b863b":{
      "scriptId":"u32"},
    "41139b3b11c84b109b5ca4b4079035c6":{
      "scriptId":"u33"},
    "c72eede64a4f48008a74e4c70d8c72f4":{
      "scriptId":"u34"},
    "2fa0742f3c1e42fa8c1b118876560f00":{
      "scriptId":"u35"},
    "2e78827c7ed34725b579398974d5e2be":{
      "scriptId":"u36"},
    "e2980584508645288f286f02eb630389":{
      "scriptId":"u37"},
    "444782e816634562b39346372fbe9be3":{
      "scriptId":"u38"},
    "6ca1f4e8eafe457dbba374c3ba02a0e3":{
      "scriptId":"u39"},
    "f9f2d10dcfb244e796bdfa465a2cedb2":{
      "scriptId":"u40"},
    "773d07981eb84905bdf8402b3709055e":{
      "scriptId":"u41"},
    "8863002775c341019bb8980c639db999":{
      "scriptId":"u42"},
    "3046b44e6d454374a76bfdde5cc8f92f":{
      "scriptId":"u43"},
    "8fbb644d67ef44e3a6a1e4b3914e6a99":{
      "scriptId":"u44"},
    "e9f2932248b646cfa61c398ba63cc1e5":{
      "scriptId":"u45"},
    "e75b6bf645f843a68426dc55c2390319":{
      "scriptId":"u46"},
    "af11b472a79d4e3b8b9939fedd1767c4":{
      "scriptId":"u47"},
    "365f9b44b0f34dd383a7e29412a30dd7":{
      "scriptId":"u48"},
    "3367eaafee59456db7f51b9ee2ad2c49":{
      "scriptId":"u49"},
    "fec887d2f2e948e09f00137ab8b6202d":{
      "scriptId":"u50"},
    "ad8acf4c0ec44cc8879324c8d920c564":{
      "scriptId":"u51"},
    "dd3e6fdb76184181b6f3b4c8e2122109":{
      "scriptId":"u52"},
    "c1ecd6ed518843febc9290398e5bbb61":{
      "scriptId":"u53"},
    "39dcc50dcab64479979e89ad2539041a":{
      "scriptId":"u54"},
    "41c4291aa9aa4eb7aeb3bffb805ceacd":{
      "scriptId":"u55"},
    "4b1f26e8580443aaa4e1d65d165cec7c":{
      "scriptId":"u56"},
    "b4a6fa044d494d40897b1d88ba9f5ea3":{
      "scriptId":"u57"},
    "3887003dbc02470ca738b9fc4855933f":{
      "scriptId":"u58"},
    "30cf6c1c6cf243f989f891b82e15dae0":{
      "scriptId":"u59"},
    "1dad18ccb7044358baf90ac278653aa5":{
      "scriptId":"u60"},
    "0ad177ba3f2f44ce944740e69d2463fb":{
      "scriptId":"u61"},
    "c9eab07c7e694be7ac0a114d6a348ecd":{
      "scriptId":"u62"},
    "e41ba5166f7641239a6bc19503c5afbd":{
      "scriptId":"u63"},
    "e93467f6f31e4957a5835569d0bdfd1a":{
      "scriptId":"u64"},
    "7eec22ec501140f09b6c7242eb27142f":{
      "scriptId":"u65"},
    "7e828bad83be48fe9e2406c7aa2153b0":{
      "scriptId":"u66"},
    "ccad348ec7964908bad29f5a41a2fa8a":{
      "scriptId":"u67",
      "cf36703323f84d5da0ce305eb182243e":{
        "scriptId":"u68"},
      "92f36235e937429f927d3bc44ef581ce":{
        "scriptId":"u69"},
      "e8721cdf67cb4fb1893fb7ecd42e1508":{
        "scriptId":"u70"},
      "5593caf6b6b942d5a16e962a1ff9225f":{
        "scriptId":"u71"},
      "1e13684f9cde432b9af9ff2a2cbb951e":{
        "scriptId":"u72"},
      "074ed56cac3f4bd3a1db4cd2db90be85":{
        "scriptId":"u73"},
      "ee7b1c95956747db81d43c22427a046d":{
        "scriptId":"u74"},
      "c5567bf4d2894ac8bac3e7e3e270f43a":{
        "scriptId":"u75"},
      "957b9c5f50644e83bd97d36c40341a9d":{
        "scriptId":"u76"},
      "b92c3b0bdb81435b855b410bc712bcb3":{
        "scriptId":"u77"},
      "f68dea9c69bd450ab354f08dc9755c6e":{
        "scriptId":"u78"},
      "6fd6f29cac81424d821b64d82b778a9c":{
        "scriptId":"u79"},
      "f7a0ac41e312402b9055d9b720c63f14":{
        "scriptId":"u80"},
      "45a480de6a584173a81c25899a5ec914":{
        "scriptId":"u81"},
      "fa6acc37cd7c4e1bb7684fcfd584b746":{
        "scriptId":"u82"},
      "d802ab836a0e4cfe9f2ca5738e0c6b96":{
        "scriptId":"u83"},
      "7d8f1f8447844dc0883e7817fa70ed53":{
        "scriptId":"u84"},
      "b69c5652827943c6a9650955bda3dc52":{
        "scriptId":"u85"},
      "ef3af0ed24b8426fb01a6e4018215ff5":{
        "scriptId":"u86"},
      "2092eb4d66124ed48789ad98e6c8129a":{
        "scriptId":"u87"}},
    "82d0db73e4ab468d9d4d42273fe4c786":{
      "scriptId":"u88"},
    "d1377580c4964b178578c5c61cf757b7":{
      "scriptId":"u89"},
    "181a51c6852d4345b2af012dbe4f3ef5":{
      "scriptId":"u90"},
    "3c191a1e114947bd8dfc167ca6f1daff":{
      "scriptId":"u91"},
    "3940464547ff4bcfa5bfa88d6e21d4ae":{
      "scriptId":"u92"},
    "e46b61a7684a40518fc1f4305dfe730a":{
      "scriptId":"u93"},
    "84f60f2b764a4a26b6938dfd6cb94bf6":{
      "scriptId":"u94"},
    "42cd09d72dec4163ab779f23c9a9d7cc":{
      "scriptId":"u95"},
    "de60f6d0c9db4320883a2d7282248856":{
      "scriptId":"u96"},
    "f5c2bd71f72345fdb5061f6d62f91264":{
      "scriptId":"u97"},
    "32e3fe3e820f4386b64eee0fa929c316":{
      "scriptId":"u98"},
    "4e42e66a7a5c43ed9d306c0e1606a97d":{
      "scriptId":"u99"},
    "94d91d85e9f54404a52fd8a38ec9cf28":{
      "scriptId":"u100"},
    "9c868d7af5104c1fad79a8fa2965927d":{
      "scriptId":"u101"},
    "437e1a5fb53a4f45934d828865a0fcdc":{
      "scriptId":"u102"},
    "3316172fd1e74cce84c13b93c812543a":{
      "scriptId":"u103"},
    "c9d5de06c1714faf89b59fab251a5357":{
      "scriptId":"u104"},
    "ebbafca1f32e444faafebbffa9ff8d6f":{
      "scriptId":"u105"},
    "2e961e49df2a43eeb3bad0bf9c4985ed":{
      "scriptId":"u106"},
    "7eea246128384f2d96c7b4774be54a78":{
      "scriptId":"u107"},
    "eb69c3fb500e4fc694da9f37049fde95":{
      "scriptId":"u108"},
    "51b25f852bf04e00a539ca788514eaee":{
      "scriptId":"u109"},
    "eb5971349ef844abaac52f3d908fc82b":{
      "scriptId":"u110"},
    "0b42320f900343ae948b5d2a7e986567":{
      "scriptId":"u111"},
    "6dfedf5c7c1b41c7a7649cbe4f8417f5":{
      "scriptId":"u112"},
    "147672b948ef4835aa46dd8585e29c6c":{
      "scriptId":"u113"},
    "18308ae527504649b82707dd14c27a01":{
      "scriptId":"u114"},
    "3af8d9eef635442eb0a292636a2b5d9a":{
      "scriptId":"u115"},
    "073f324d68904061812580ead14a82b6":{
      "scriptId":"u116"},
    "dc83912eb95d4535b4bb8de7fc2d0e0c":{
      "scriptId":"u117"},
    "67fc779c61af4b0cb419f2057447b53c":{
      "scriptId":"u118"},
    "da3f158af2c94616bc3f4078a4c8cf69":{
      "scriptId":"u119"},
    "5869b078bbcb4e66818152fdd8423b3a":{
      "scriptId":"u120"}}});