$axure.loadCurrentPage({
  "url":"客服聊天—无客户.html",
  "generationDate":new Date(1418371264480.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"654c6795a5b7447dafabf2520b13e3a7",
    "type":"Axure:Page",
    "name":"客服聊天—无客户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2c6f2b68a63847558946ed393f6863a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":-10,
              "y":45},
            "size":{
              "width":1140,
              "height":760},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"609031f104494d60bd44526a5bbed147",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":-10,
                  "y":45},
                "size":{
                  "width":1140,
                  "height":760},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u0.png"}},
{
          "id":"bebd34e4ab484496af482f219f7bc58d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":184,
              "y":70},
            "size":{
              "width":578,
              "height":710},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7564a70004f3428a96896f7ca96a1bab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":184,
                  "y":70},
                "size":{
                  "width":578,
                  "height":710},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u2.png"}},
{
          "id":"ab92b06de9e54a1594290ef1a01f8ef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":14,
              "y":70},
            "size":{
              "width":160,
              "height":710},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb6ec0a0ae33467ba3575fe43e8b5000",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":14,
                  "y":70},
                "size":{
                  "width":160,
                  "height":710},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u6.png"}},
{
          "id":"daddcc6cc2454d42bfbf4993ec225e45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF949494,
              "opacity":1},
            "location":{
              "x":774,
              "y":70},
            "size":{
              "width":333,
              "height":710},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2c7722705004cbca39c6fb3503e28a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF949494,
                  "opacity":1},
                "location":{
                  "x":774,
                  "y":70},
                "size":{
                  "width":333,
                  "height":710},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天_知识库/u20.png"}},
{
          "id":"ebba288138164241a7dbb5797d753974",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":15,
              "y":127},
            "size":{
              "width":158,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u24_line.png"}},
{
          "id":"c60d69f1c50d4bd6a8c15f10d51eda77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":34,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1961c5103b6e44dbb448ebafda715bb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":34,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea945fc19e8844de8fd5f4c87b278d8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":793,
              "y":92},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87291b5e128f40659588216a2080cd2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":793,
                  "y":92},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80d98a8d8a7944b980c5a3a33c0d08c6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":184,
              "y":620},
            "size":{
              "width":578,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u49_line.png"}},
{
          "id":"7ea69634a8ef4ed1a215d5115c598e80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":204,
              "y":641},
            "size":{
              "width":104,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d517e4a2a354864ba0ad32b482165cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":204,
                  "y":641},
                "size":{
                  "width":104,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2efbdec5e3f14dada532cec019dc73b1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":127},
            "size":{
              "width":576,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u62_line.png"}},
{
          "id":"e98b9d2e94514a2881d72cad134e39c6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":775,
              "y":127},
            "size":{
              "width":332,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/客服聊天/u69_line.png"}},
{
          "id":"9fee2e81333d4f77b8d34f47d5dea515",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF7D7D86},
            "location":{
              "x":793,
              "y":130},
            "size":{
              "width":64,
              "height":2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10e5fe9f9b5b48789b6856b401cdbad4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF7D7D86},
                "location":{
                  "x":793,
                  "y":130},
                "size":{
                  "width":64,
                  "height":2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天/u89.png"}},
{
          "id":"8441ebb3072c43a2acc9f2657c4896d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":869,
              "y":92},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c11ffb509a3f43ce8cfe2978c4f8159b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":869,
                  "y":92},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2980584508645288f286f02eb630389",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":665,
              "y":88},
            "size":{
              "width":76,
              "height":25},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"444782e816634562b39346372fbe9be3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":665,
                  "y":88},
                "size":{
                  "width":76,
                  "height":25},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天_转接成功（转接的客服）/u108.png"}},
{
          "id":"e2909bae33374fd88c1abcd26e568dca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "opacity":"0.6",
            "location":{
              "x":362,
              "y":259},
            "size":{
              "width":127,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ac0f91d5cb4bd4ab4d556197cd02bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "opacity":"0.6",
                "location":{
                  "x":362,
                  "y":259},
                "size":{
                  "width":127,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天—无客户/u24.png"}},
{
          "id":"1e0d4bde38d84d1b9ac852c481228511",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"28px",
            "location":{
              "x":490,
              "y":296},
            "size":{
              "width":93,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eb67f7e479a4693bf7ebe5c6ad953a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"28px",
                "location":{
                  "x":490,
                  "y":296},
                "size":{
                  "width":93,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd94b9a135764d0a957cfe5899f5ebf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":904,
              "y":336},
            "size":{
              "width":74,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c80a2b39d35f4e029988bc60be304ac8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":904,
                  "y":336},
                "size":{
                  "width":74,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac5dc6ee51ed4043880e1402ff923823",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":583,
              "y":732},
            "size":{
              "width":76,
              "height":25},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a5997f500ab49b1a2aed81e314548b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":583,
                  "y":732},
                "size":{
                  "width":76,
                  "height":25},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天_转接成功（转接的客服）/u108.png"}},
{
          "id":"0e39aa9002d34a3d84f70d9ce41347bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFD7D7D7},
            "location":{
              "x":669,
              "y":732},
            "size":{
              "width":76,
              "height":25},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a77dd439e49491684c77f18df48d01f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":669,
                  "y":732},
                "size":{
                  "width":76,
                  "height":25},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客服聊天_转接成功（转接的客服）/u108.png"}},
{
          "id":"a648b9d0829440c99fee314dbbb45ae4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6a5acbfcf24142c6b12dd54905974233"}]}},
  "masters":{
    "6a5acbfcf24142c6b12dd54905974233":{
      "packageId":"6a5acbfcf24142c6b12dd54905974233",
      "type":"Axure:Master",
      "name":"Title_客服聊天（客服管理员）有消息",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"cf36703323f84d5da0ce305eb182243e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":410,
                "y":26},
              "size":{
                "width":12,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"92f36235e937429f927d3bc44ef581ce",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":410,
                    "y":26},
                  "size":{
                    "width":12,
                    "height":10},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u126.png"}},
{
            "id":"e8721cdf67cb4fb1893fb7ecd42e1508",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":260,
                "y":17},
              "size":{
                "width":120,
                "height":24},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5593caf6b6b942d5a16e962a1ff9225f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":260,
                    "y":17},
                  "size":{
                    "width":120,
                    "height":24},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1e13684f9cde432b9af9ff2a2cbb951e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFF363636},
              "location":{
                "x":240,
                "y":0},
              "size":{
                "width":890,
                "height":45},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF1B1B1B}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"074ed56cac3f4bd3a1db4cd2db90be85",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF363636},
                  "location":{
                    "x":240,
                    "y":0},
                  "size":{
                    "width":890,
                    "height":45},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF1B1B1B}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u130.png"}},
{
            "id":"ee7b1c95956747db81d43c22427a046d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFF363636},
              "size":{
                "width":240,
                "height":45},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF1B1B1B}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c5567bf4d2894ac8bac3e7e3e270f43a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF363636},
                  "size":{
                    "width":240,
                    "height":45},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFF1B1B1B}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u132.png"}},
{
            "id":"957b9c5f50644e83bd97d36c40341a9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":951,
                "y":14},
              "size":{
                "width":52,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b92c3b0bdb81435b855b410bc712bcb3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":951,
                    "y":14},
                  "size":{
                    "width":52,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 客服聊天_编辑admin in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"客服聊天_编辑admin.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f68dea9c69bd450ab354f08dc9755c6e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFFBCBCBC},
              "location":{
                "x":917,
                "y":11.5},
              "size":{
                "width":22,
                "height":22},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "cornerRadiusTopLeft":"5"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6fd6f29cac81424d821b64d82b778a9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFBCBCBC},
                  "location":{
                    "x":917,
                    "y":11.5},
                  "size":{
                    "width":22,
                    "height":22},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "cornerRadiusTopLeft":"5"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u136.png"}},
{
            "id":"f7a0ac41e312402b9055d9b720c63f14",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":921,
                "y":15.5},
              "size":{
                "width":15,
                "height":15},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45a480de6a584173a81c25899a5ec914",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":921,
                    "y":15.5},
                  "size":{
                    "width":15,
                    "height":15},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u138.png"}},
{
            "id":"fa6acc37cd7c4e1bb7684fcfd584b746",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":807,
                "y":14},
              "size":{
                "width":83,
                "height":16},
              "rotation":"0",
              "textRotation":"0"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d802ab836a0e4cfe9f2ca5738e0c6b96",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":807,
                    "y":14},
                  "size":{
                    "width":83,
                    "height":16},
                  "rotation":"0",
                  "textRotation":"0"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"Open 客服聊天—消息 in Current Window",
                        "target":{
                          "targetType":"page",
                          "url":"客服聊天—消息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7d8f1f8447844dc0883e7817fa70ed53",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFFB00000},
              "location":{
                "x":829,
                "y":8},
              "size":{
                "width":14,
                "height":14},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b69c5652827943c6a9650955bda3dc52",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFB00000},
                  "location":{
                    "x":829,
                    "y":8},
                  "size":{
                    "width":14,
                    "height":14},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/客服聊天/u142.png"}},
{
            "id":"ef3af0ed24b8426fb01a6e4018215ff5",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"12px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":833,
                "y":8},
              "size":{
                "width":8,
                "height":15}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2092eb4d66124ed48789ad98e6c8129a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"12px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":833,
                    "y":8},
                  "size":{
                    "width":8,
                    "height":15}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "2c6f2b68a63847558946ed393f6863a4":{
      "scriptId":"u0"},
    "609031f104494d60bd44526a5bbed147":{
      "scriptId":"u1"},
    "bebd34e4ab484496af482f219f7bc58d":{
      "scriptId":"u2"},
    "7564a70004f3428a96896f7ca96a1bab":{
      "scriptId":"u3"},
    "ab92b06de9e54a1594290ef1a01f8ef4":{
      "scriptId":"u4"},
    "eb6ec0a0ae33467ba3575fe43e8b5000":{
      "scriptId":"u5"},
    "daddcc6cc2454d42bfbf4993ec225e45":{
      "scriptId":"u6"},
    "a2c7722705004cbca39c6fb3503e28a0":{
      "scriptId":"u7"},
    "ebba288138164241a7dbb5797d753974":{
      "scriptId":"u8"},
    "c60d69f1c50d4bd6a8c15f10d51eda77":{
      "scriptId":"u9"},
    "1961c5103b6e44dbb448ebafda715bb2":{
      "scriptId":"u10"},
    "ea945fc19e8844de8fd5f4c87b278d8c":{
      "scriptId":"u11"},
    "87291b5e128f40659588216a2080cd2b":{
      "scriptId":"u12"},
    "80d98a8d8a7944b980c5a3a33c0d08c6":{
      "scriptId":"u13"},
    "7ea69634a8ef4ed1a215d5115c598e80":{
      "scriptId":"u14"},
    "5d517e4a2a354864ba0ad32b482165cb":{
      "scriptId":"u15"},
    "2efbdec5e3f14dada532cec019dc73b1":{
      "scriptId":"u16"},
    "e98b9d2e94514a2881d72cad134e39c6":{
      "scriptId":"u17"},
    "9fee2e81333d4f77b8d34f47d5dea515":{
      "scriptId":"u18"},
    "10e5fe9f9b5b48789b6856b401cdbad4":{
      "scriptId":"u19"},
    "8441ebb3072c43a2acc9f2657c4896d7":{
      "scriptId":"u20"},
    "c11ffb509a3f43ce8cfe2978c4f8159b":{
      "scriptId":"u21"},
    "e2980584508645288f286f02eb630389":{
      "scriptId":"u22"},
    "444782e816634562b39346372fbe9be3":{
      "scriptId":"u23"},
    "e2909bae33374fd88c1abcd26e568dca":{
      "scriptId":"u24"},
    "89ac0f91d5cb4bd4ab4d556197cd02bf":{
      "scriptId":"u25"},
    "1e0d4bde38d84d1b9ac852c481228511":{
      "scriptId":"u26"},
    "4eb67f7e479a4693bf7ebe5c6ad953a6":{
      "scriptId":"u27"},
    "bd94b9a135764d0a957cfe5899f5ebf2":{
      "scriptId":"u28"},
    "c80a2b39d35f4e029988bc60be304ac8":{
      "scriptId":"u29"},
    "ac5dc6ee51ed4043880e1402ff923823":{
      "scriptId":"u30"},
    "5a5997f500ab49b1a2aed81e314548b5":{
      "scriptId":"u31"},
    "0e39aa9002d34a3d84f70d9ce41347bb":{
      "scriptId":"u32"},
    "0a77dd439e49491684c77f18df48d01f":{
      "scriptId":"u33"},
    "a648b9d0829440c99fee314dbbb45ae4":{
      "scriptId":"u34",
      "cf36703323f84d5da0ce305eb182243e":{
        "scriptId":"u35"},
      "92f36235e937429f927d3bc44ef581ce":{
        "scriptId":"u36"},
      "e8721cdf67cb4fb1893fb7ecd42e1508":{
        "scriptId":"u37"},
      "5593caf6b6b942d5a16e962a1ff9225f":{
        "scriptId":"u38"},
      "1e13684f9cde432b9af9ff2a2cbb951e":{
        "scriptId":"u39"},
      "074ed56cac3f4bd3a1db4cd2db90be85":{
        "scriptId":"u40"},
      "ee7b1c95956747db81d43c22427a046d":{
        "scriptId":"u41"},
      "c5567bf4d2894ac8bac3e7e3e270f43a":{
        "scriptId":"u42"},
      "957b9c5f50644e83bd97d36c40341a9d":{
        "scriptId":"u43"},
      "b92c3b0bdb81435b855b410bc712bcb3":{
        "scriptId":"u44"},
      "f68dea9c69bd450ab354f08dc9755c6e":{
        "scriptId":"u45"},
      "6fd6f29cac81424d821b64d82b778a9c":{
        "scriptId":"u46"},
      "f7a0ac41e312402b9055d9b720c63f14":{
        "scriptId":"u47"},
      "45a480de6a584173a81c25899a5ec914":{
        "scriptId":"u48"},
      "fa6acc37cd7c4e1bb7684fcfd584b746":{
        "scriptId":"u49"},
      "d802ab836a0e4cfe9f2ca5738e0c6b96":{
        "scriptId":"u50"},
      "7d8f1f8447844dc0883e7817fa70ed53":{
        "scriptId":"u51"},
      "b69c5652827943c6a9650955bda3dc52":{
        "scriptId":"u52"},
      "ef3af0ed24b8426fb01a6e4018215ff5":{
        "scriptId":"u53"},
      "2092eb4d66124ed48789ad98e6c8129a":{
        "scriptId":"u54"}}}});