$axure.loadCurrentPage({
  "url":"sign_in.html",
  "generationDate":new Date(1418371260789.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a51c6c1353284452a01aa87b826503ab",
    "type":"Axure:Page",
    "name":"sign in",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0afb8b7b52ad424da05f615537d0c394",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFF37C4A9},
            "location":{
              "x":-10,
              "y":0},
            "size":{
              "width":1010,
              "height":810},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12b2cbe6d96744b28221fe2cd14c8096",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF37C4A9},
                "location":{
                  "x":-10,
                  "y":0},
                "size":{
                  "width":1010,
                  "height":810},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_in/u0.png"}},
{
          "id":"075d49b0c5cb401da380218493c269ff",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":298,
              "y":-40},
            "size":{
              "width":393,
              "height":520}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"015aca8d73704dd2ac1ee277c234ff9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":298,
                  "y":-40},
                "size":{
                  "width":393,
                  "height":520}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_in/u2.png"}},
{
          "id":"ec9ffaa17dcc4617bbb2f080711584ff",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":328,
              "y":255},
            "size":{
              "width":320,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1b683d3a582b442d98b4292fa8f931dc",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":328,
              "y":300},
            "size":{
              "width":320,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dbfe68e7aa0945318a4c21021a748b79",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":328,
              "y":345},
            "size":{
              "width":130,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19958ffc3772452086388767d0366732",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":328,
                  "y":345},
                "size":{
                  "width":130,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e81765a0d4d24dcba49f14fba919b43f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF75C25A},
            "location":{
              "x":328,
              "y":381},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"155fe96313b54b78a5ac6cafa8496aee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF75C25A},
                "location":{
                  "x":328,
                  "y":381},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/sign_in/u8.png"}},
{
          "id":"a2fa091939be4001bcca1210116d088c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":542,
              "y":388},
            "size":{
              "width":106,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe5069d81dbc4b72bb402fbad2960d3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":542,
                  "y":388},
                "size":{
                  "width":106,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0afb8b7b52ad424da05f615537d0c394":{
      "scriptId":"u0"},
    "12b2cbe6d96744b28221fe2cd14c8096":{
      "scriptId":"u1"},
    "075d49b0c5cb401da380218493c269ff":{
      "scriptId":"u2"},
    "015aca8d73704dd2ac1ee277c234ff9d":{
      "scriptId":"u3"},
    "ec9ffaa17dcc4617bbb2f080711584ff":{
      "scriptId":"u4"},
    "1b683d3a582b442d98b4292fa8f931dc":{
      "scriptId":"u5"},
    "dbfe68e7aa0945318a4c21021a748b79":{
      "scriptId":"u6"},
    "19958ffc3772452086388767d0366732":{
      "scriptId":"u7"},
    "e81765a0d4d24dcba49f14fba919b43f":{
      "scriptId":"u8"},
    "155fe96313b54b78a5ac6cafa8496aee":{
      "scriptId":"u9"},
    "a2fa091939be4001bcca1210116d088c":{
      "scriptId":"u10"},
    "fe5069d81dbc4b72bb402fbad2960d3d":{
      "scriptId":"u11"}}});