---
global_vars:
  nginx:
    sites:
      - name: www.quncrm.com
        conf_path: deploy/nginx/cp.conf
  mongodb:
    db:
      name: augmarketing
      username: aug
      password: augabc123_
    host: db1
    port: 27017

  settings:
    mail:
      api_user: quncrm_portal
      api_key: MO0JLapIEPmlKGpZ
      from: no-reply@quncrm.com
      from_name: 群脉

  global:
    current_env: prod

  log:
    file_log: 2
    level: error
    frontend:
      track_url: https://www.quncrm.com/api/log/frontend
    sls:
      endpoint: cn-hangzhou.sls.aliyuncs.com
      access_key_id: HCY16IorxExaTugH
      access_key_secret: 7uG7gJ1APOlbL5ZXuGTUaVqxhhndVY
      project_id: omnisocials
      log_store: errorlogs
      log_topic: WebPortal

  redis:
    host: afea1eebebd649b6.m.cnhza.kvstore.aliyuncs.com
    port: 6379

  resque:
    host: afea1eebebd649b6.m.cnhza.kvstore.aliyuncs.com
    port: 6379
    db: 2
    passwd: "'afea1eebebd649b6:AugRedis123'"

  cache:
    host: afea1eebebd649b6.m.cnhza.kvstore.aliyuncs.com
    port: 6379
    db: 1
    passwd: "'afea1eebebd649b6:AugRedis123'"

  crons:
    - name: "Those command which is perform once a minute"
      schedules:
        minute:  "*/1"
      job: "<< repo.path >>/src/yii cron/minute > /dev/null 2>&1"
      state: absent
      host_name: as6
    - name: "Those command which is perform once a day"
      schedules:
        minute: "0"
        hour:  "1"
      job: "<< repo.path >>/src/yii cron/daily > /dev/null 2>&1"
      state: present
      host_name: as6
    - name: "automatic clear member score"
      schedules:
        minute: "59"
        hour:  "23"
      job: "<< repo.path >>/src/yii cron/daily/reset-score > /dev/null 2>&1"
      state: absent
      host_name: as6

  qiniu:
    domain: https://dn-quncrm.qbox.me
    private_domain: 7xjigt.dl1.z0.glb.clouddn.com
    bucket: quncrm
    private_bucket: omnisocials
    access_key: Ft6PlywyvrQDZWc0kdc7nFuJYB4Hcm38Yy68oiFf
    secret_key: o2SriW2EoujXHSadCPHbEJsvpVo2vPzEYAHd8A3N
    upload_domain: https://up.qbox.me
    thumbnail_lite: ?imageView2/0/w/50
    thumbnail_small: ?imageView2/0/w/200
    thumbnail_middle: ?imageView2/0/w/400

  shorturl:
    domain: https://u.quncrm.com

  wechat:
    domain: http://wx.quncrm.com
    jssdk:
      app_id: wx2d1e974db806d030
      app_secret: 3e04171d2125aa8d74d88f63f8cb36e7
      domain: https://www.quncrm.com/
      channel_id: 55a60bda0cf2fc20bbf8feae

  weibo:
    app_key: 2234053950
    app_secret: 529561c4fd0ad5086412657278dede40
    redirect_url: /management/oauth2/accesstoken

  webhook:
    domain: https://api.quncrm.com
    host: api.quncrm.com

  tuisongbao:
    domain: https://api.tuisongbao.com
    app_id: 54d04f4605b874fd7942fc06
    secret: 495857ac0d1996ac48a1ff98
    push_app_id: 551b4f48e944fbf0571b0b06
    push_secret: 4a6b5454a977e1dd1a5087ae

  yunpian:
    domain: http://yunpian.com/v1/sms/send.json
    api_key: c87163327283e2dc44d3cfe71a251cde

  supervisor:
    sock: unix:///var/run//supervisor.sock
    conf: /etc/supervisor/conf.d/<< repo.name >>.conf
    group: << repo.name >>

  helpdesk:
    account_id: 54f6cfef8f5e88b96a8b4567

deploy_vars:
  mongodb:
    hosts:
      - group: mongodb_standalone
        hosts:
          - name: << mongodb.host >>
            vars:
              mongodb:
                instance:
                  name: mongodb
                  port: << mongodb.port >>
        vars:
          mongodb:
            dbs:
              - << mongodb.db >>
  web_nginx_php5fpm:
    hosts:
      - name: as6
        vars:
          internal_iface: eth1
      - name: as10
        vars:
          internal_iface: eth1
  redis:
    require: False
  worker:
    hosts:
      - name: as6
      - name: as10
  cron:
    hosts:
      - name: as6