site_name: OmniSocial Directives
pages:
- 'Index': 'index.md'
- 'Common Directives':
    - 'wmCheckbox': 'directives/wm-checkbox.md'
    - 'wmRadio': 'directives/wm-radio.md'
    - 'wmCopyInput': 'directives/wm-copy-input.md'
    - 'wmLocation': 'directives/wm-location.md'
    - 'wmDatetimePicker': 'directives/wm-datetime-picker.md'
    - 'wmInputReg': 'directives/wm-input-reg.md'
    - 'wmTooltip': 'directives/wm-tooltip.md'
    - 'wmBreadcrumb': 'directives/wm-breadcrumb.md'
    - 'wmFileUpload': 'directives/wm-file-upload.md'
    - 'wmQrcode': 'directives/wm-qrcode.md'
    - 'wmQrcodeDownload': 'directives/wm-qrcode-download.md'
    - 'wmMultiQrcode': 'directives/wm-multi-qrcode.md'
    - 'wmTable & wmFixedTable': 'directives/wm-table.md'
    - 'wmSelect': 'directives/wm-select.md'
    - 'wmFormValidation': 'directives/wm-form-validation.md'
    - 'wmSearch': 'directives/wm-search.md'
- 'Uncommon Directives':
    - 'wmWechatMessage': 'directives/wm-wechat-message.md'
    - 'wmSlider': 'directives/wm-slider.md'
    - 'wmCenterImg': 'directives/wm-center-img.md'
    - 'wmColorPicker': 'directives/wm-color-picker.md'
    - 'wmCopy': 'directives/wm-copy.md'
    - 'wmQuarterPicker': 'directives/wm-quarter-picker.md'
    - 'wmWechatGraphic': 'directives/wm-wechat-graphic.md'
    - 'wmPictureShow': 'directives/wm-picture-show.md'
    - 'wmLabel': 'directives/wm-label.md'
    - 'wmEnter': 'directives/wm-enter.md'
    - 'wmMicrositeLocation': 'directives/wm-microsite-location.md'
    - 'wmMicrositeColorPicker': 'directives/wm-microsite-color-picker.md'
    - 'wmPageColorPicker': 'directives/wm-page-color-picker.md'
    - 'wmSelectTable': 'directives/wm-select-table.md'
    - 'wmSwitch': 'directives/wm-switch.md'
    - 'wmWaterfall': 'directives/wm-waterfall.md'
    - 'wmMaxlength': 'directives/wm-maxlength.md'
    - 'wmPictureLib': 'directives/wm-picture-lib.md'
    - 'wmAutoComplete': 'directives/wm-auto-complete.md'
    - 'wmChannelQrcode': 'directives/wm-channel-qrcode.md'
    - 'wmLinkSelect': 'directives/wm-link-select.md'
    - 'wmDraggable': 'directives/wm-draggable.md'
    - 'wmStore': 'directives/wm-store.md'
    - 'wmSortable': 'directives/wm-sortable.md'
- 'Filters':
    - 'numberFilter': 'filters/number-filter.md'
- 'Services':
    - 'notificationService': 'services/notification-service.md'
- 'About':
    'about.md'
theme: mkdocs
